// <auto-generated />
namespace DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class spSearchDetailoffertraining : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(spSearchDetailoffertraining));
        
        string IMigrationMetadata.Id
        {
            get { return "202105220957207_sp-SearchDetailoffertraining"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
